# fly.toml app configuration file generated for ausa on 2025-03-30T14:47:14+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ausa'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
