# fly.toml app configuration file generated for ausa-api on 2025-06-08T15:52:28+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ausa-api'
primary_region = 'syd'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
max_machines_running = 1
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
