name: Fly Deploy Server
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-server
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set secrets
        run: flyctl secrets set --config server/fly.server.toml "FIREBASE_SERVICE_ACCOUNT_JSON=$(echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }} | base64 --decode)"

      - name: Deploy secrets to server
        run: flyctl secrets deploy --config server/fly.server.toml

      - name: Deploy server to Fly
        run: flyctl deploy --remote-only --config server/fly.server.toml

