# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Client
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: Production
    concurrency:
      group: deploy-client
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config client/fly.client.toml

  finalize-deployment:
    name: Finalize Deployment
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    steps:
      - name: Create Deployment via GitHub API
        id: create
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
              "ref": "${{ github.sha }}",
              "environment": "Production",
              "required_contexts": [],
              "auto_merge": false,
              "description": "Deploying AUSA app to production"
            }')
          echo "deployment_id=$(echo $response | jq -r '.id')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mark Deployment as Success
        if: success()
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ steps.create.outputs.deployment_id }}/statuses \
            -d '{"state": "success"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mark Deployment as Failure
        if: failure()
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ steps.create.outputs.deployment_id }}/statuses \
            -d '{"state": "failure"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
